export const FETCH_DATA = "FETCH_DATA",
  FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA",
  SET_DATA = "SET_DATA",
  SET_SEARCH_DATA = "SET_SEARCH_DATA",
  RESET_SEARCH_DATA = "RESET_SEARCH_DATA",
  SEND_DATA = "SEND_DATA";

export const FETCH_INDIVIDUAL_HOME_DATA = "FETCH_INDIVIDUAL_HOME_DATA",
  FETCH_INDIVIDUAL_EXPERIENCE_DATA = "FETCH_INDIVIDUAL_EXPERIENCE_DATA",
  FETCH_RESTAURANT_DATA = "FETCH_RESTAURANT_DATA",
  SET_RESTAURANT_DATA = "SET_RESTAURANT_DATA",
  SET_INDIVIDUAL_HOME_DATA = "SET_INDIVIDUAL_HOME_DATA",
  SET_INDIVIDUAL_EXPERIENCE_DATA = "SET_INDIVIDUAL_EXPERIENCE_DATA",
  RESET_INDIVIDUAL_DATA = "RESET_INDIVIDUAL_DATA";

export const SEARCH_PAGE_LOADING_FALSE = "SEARCH_PAGE_LOADING_FALSE";

export const TOGGLE_GUESTS_DROPDOWN_HOME = "TOGGLE_GUESTS_DROPDOWN_HOME",
  TOGGLE_GUESTS_DROPDOWN_RESTAURANT = "TOGGLE_GUESTS_DROPDOWN_RESTAURANT",
  INCREASE_HOME_GUEST_COUNT_ADULTS = "INCREASE_HOME_GUEST_COUNT_ADULTS",
  DECREASE_HOME_GUEST_COUNT_ADULTS = "DECREASE_HOME_GUEST_COUNT_ADULTS",
  DECREASE_HOME_GUEST_COUNT_CHILDREN = "DECREASE_HOME_GUEST_COUNT_CHILDREN",
  INCREASE_HOME_GUEST_COUNT_CHILDREN = "INCREASE_HOME_GUEST_COUNT_CHILDREN",
  DECREASE_HOME_GUEST_COUNT_INFANTS = "DECREASE_HOME_GUEST_COUNT_INFANTS",
  INCREASE_HOME_GUEST_COUNT_INFANTS = "INCREASE_HOME_GUEST_COUNT_INFANTS",
  INCREASE_RESTAURANT_GUEST_COUNT = "INCREASE_RESTAURANT_GUEST_COUNT",
  DECREASE_RESTAURANT_GUEST_COUNT = "DECREASE_RESTAURANT_GUEST_COUNT";
  