export const FETCH_DATA = "FETCH_DATA",
  FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA",
  SET_DATA = "SET_DATA",
  SET_SEARCH_DATA = "SET_SEARCH_DATA",
  RESET_SEARCH_DATA = "RESET_SEARCH_DATA",
  SEND_DATA = "SEND_DATA";

export const FETCH_INDIVIDUAL_HOME_DATA = "FETCH_INDIVIDUAL_HOME_DATA",
  FETCH_INDIVIDUAL_EXPERIENCE_DATA = "FETCH_INDIVIDUAL_EXPERIENCE_DATA",
  SET_INDIVIDUAL_HOME_DATA = "SET_INDIVIDUAL_HOME_DATA",
  SET_INDIVIDUAL_EXPERIENCE_DATA = "SET_INDIVIDUAL_EXPERIENCE_DATA",
  RESET_INDIVIDUAL_DATA = "RESET_INDIVIDUAL_DATA";